const TABLE_RESIZE = 'TABLE_RESIZE'
const CHANGE_TEXT = 'CHANGE_TEXT'
const APPLY_STYLE = 'APPLY_STYLE'
const CHANGE_STYLES = 'CHANGE_STYLES'
const CHANGE_TITLE = 'CHANGE_TITLE'

export {TABLE_RESIZE, CHANGE_TEXT, CHANGE_STYLES, APPLY_STYLE, CHANGE_TITLE}